### ISSUE TITLE
signal transduction pathway

### ISSUE THREAD

**Issue by rojinsafavi** [reactome/reactome2py#30]
I was wondering if there is a way to load a signal transduction pathway using the tool?

**Comment by teslajoy** [comment]
sure - if you don't need the event hierarchy structure and don't know the Reactome stId associated with the pathway/event you'd like, I would recommend ex: 

```python 
from reactome2py import fiviz, content
import pandas as pd

df = pd.DataFrame(fiviz.gene_mappings())
df[df.name.isin(['Signal Transduction'])]
``` 

if you know the stId of the event, then possibly one of these two functions:
```python 
content.pathway_contained_event(id='R-HSA-162582')
content.pathway_contained_event_atttibute(id='R-HSA-162582', attribute='name')
```
